
CREATE TABLE medicine
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    manufacturer VARCHAR(255),
    stock        INTEGER,
    CONSTRAINT pk_medicine PRIMARY KEY (id)
);